### ISSUE TITLE
deprecation warning for set-env

### ISSUE THREAD

**Issue by jhartzell** [codfish/semantic-release-action#128]
```
Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Do the maintainers of this project have plans to fix this before the deadline?

**Comment by codfish** [comment]
@jhartzell yep, upgraded :)

https://github.com/codfish/semantic-release-action/pull/132

**Comment by codfish** [comment]
@jhartzell you can re-run any workflows that output any warnings or errors, but should be fine moving forward!
