### ISSUE TITLE
Pre-built Docker image

### ISSUE THREAD

**Issue by lholota** [codfish/semantic-release-action#142]
## Problem
Currently the Docker image for the action is built ad-hoc for each execution. Given that it installs npm modules, it takes around a 45-60 seconds on average. 

## Suggestion
I would suggest building this image and pushing it to DockerHub (and also Quay.io given the restrictions DockerHub is about to enable) so that the image is just pulled. AFAIK GitHub caches some of the Docker images in their infra which would make it even faster.

**Comment by codfish** [comment]
> DockerHub (and also Quay.io given the restrictions DockerHub is about to enable)

@lholota thanks for opening the issue, it's a great idea. Mind me asking:

1. what restrictions?
2. Even if I deploy to multiple locations, say dockerhub, quay and/or GitHub package registry, it would be up to the end user to pick right? And you're saying along with doing this, in order to get the benefit, a user would need to specify the artifact's url instead of codfish/semantic-release-action, right?

**Comment by franky47** [comment]
You could probably deploy to GitHub's container registry, it would make more sense to "keep it in the family", download times might be even further reduced.

The restriction could be about DockerHub's new pricing strategy and rate-limiting:
https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/

**Comment by codfish** [comment]
hey @franky47 @lholota, https://github.com/codfish/actions-playground/blob/master/.github/workflows/release.yml#L38

I've got it running on dockerhub already, so we can use that immediately. Need to update actions to auto build & deploy to gpr as well, and i'll open up a PR to update the docs to promote these two options as well. I'm in the process of changing jobs so I've got some things taking my attention so might be a week or so. Either of you are also welcome to contribute these changes if you're interested & have time!

**Comment by lholota** [comment]
@franky47 @codfish 
Yep, the restrictions are about the pull limit on a public image from one account/IP. 

Given that all actions are executed on the same pool of runners, they are behind the a limited number of public IPs and might get throttled which is why internally I would suggest using quay as the source until it's certain how the limits will impact GitHub actions.

My assumption is that GitHub will create some local cache for Docker images, but I haven't heard of any announcement so far...

I'll try to contribute when there's free time, but I can't really test it as that would require access to your slug in Dockerhub and Quay

**Comment by codfish** [comment]
@franky47 @lholota @moul better late than never! pre-built docker images available on GHCR and docker hub

https://github.com/codfish/actions-playground/runs/1798449926?check_suite_focus=true

`~45s` image build --> `~4s` pull 💯 💯 💯

**Comment by franky47** [comment]
Awesome, thanks !
