### ISSUE TITLE
Does branch input do anything?

### ISSUE THREAD

**Issue by thesmiley1** [codfish/semantic-release-action#145]
I was looking through this action and found myself confused by the `branch` input that it accepts.  I couldn't find any documentation for it from `semantic-release`, just `branches`.

I think part of my confusion stems from the fact that I am new to semantic-release.  I checked their release notes and noticed that in [version 16](https://github.com/semantic-release/semantic-release/releases/tag/v16.0.0) they dropped `branch` in favor of `branches`.

If I'm understanding correctly how GitHub Actions works, this action will always use `^17.x.x`, according to its `package.json`.  I think this all points to the `branch` input not doing anything and should be removed?

---

Possibly moot, but what was the use case for this?  It seems likes it's just overriding `.releaserc`, so I think I'm still missing something.

**Comment by codfish** [comment]
@thesmiley1 hey man, sorry for poor response time here, everything's been updated to support v16 and v17 of semantic release and the `branch` input was just from previous versions. I've kept it in there for backwards compat so as to not break v1 of the action, but now there's support for [other inputs as well](https://github.com/codfish/semantic-release-action#configuration), including the newer `branches` option.

> Possibly moot, but what was the use case for this? It seems likes it's just overriding .releaserc, so I think I'm still missing something.

So use cases might be if you didn't want to include a config file in your repo, and you're only running this in ci/cd anyway, you can just configure any overrides to the defaults directly in actions OR in certain workflows, i.e. different branches or different github events where you may want to override certain configuration options, like the tag format, or if you wanted to run the release in dryRun mode to validate if a PR will release properly or something like that.

Either way though, I'm sure someone will have a use for it and I'm just accepting those inputs and providing them to semantic release.

you can see all the magic here https://github.com/codfish/semantic-release-action/blob/master/entrypoint.js
