### ISSUE TITLE
Outputs should get set even when no new release is created

### ISSUE THREAD

**Issue by EuleMitKeule** [codfish/semantic-release-action#179]
I think it would be better if the release-version and other outputs would be set to the calculated version even if no new release is created.
Or at  least it should be noted in the readme that this is not the case.

**Comment by codfish** [comment]
@EuleMitKeule could you elaborate on your expected behavior in the event a new version is NOT created? It should still set the outputs but the values should be the current version?

**Comment by EuleMitKeule** [comment]
Sure! As I understand semantic-release will calculate a version number consisting of a major, minor and patch version number. Your action then will assign these values to the action outputs `release-version`, `release-major`, `release-minor` and `release-patch`.
The current behaviour of you action is that these values will only be assigned, if the calculated version number did not lead to a release creation in the past. In my opinion, this condition is unnecessary, since the value of the output variable `new-release-published` already tells us whether a release was created or not.
Maybe you could imagine a case where the user would want to run another step that depends on the calculated version number regardless of whether a release was created or not. Doing this using the `semantic-release-action` is currently not possible, if I understand correctly, since the `release-version`, `release-major`, `release-minor` and `release-patch` output variables will currently contain no value at all, except when a release/tag was actually created.

**Comment by codfish** [comment]
@EuleMitKeule Gotcha. I see no issue with setting those outputs if they're there but if I remember correctly the sdk doesn't return them when there's no new version. Maybe that's changed though so let me test it out again

**Comment by codfish** [comment]
https://github.com/codfish/semantic-release-action/blob/main/entrypoint.js#L94

Unfortunately semantic release may log the current version but it doesn't return it from the lib if no new release is published.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/semantic-release/index.d.ts#L608

```js
/**
 * An object with details of the release if a release was published, or
 * false if no release was published.
 */
```

I think you could go about getting the latest release another way if you really need it when a new release isn't published, via `git describe --abbrev=0 --tags` (make sure you update `actions/checkout` to pull down more than just the HEAD).

![image](https://user-images.githubusercontent.com/1666298/229315543-44811bb5-3531-49c8-bf75-0eafa334b9db.png)

But at this time, if semantic doesn't support this, it's not something I'd look to add to this action

**Comment by strazto** [comment]
This issue affects my CI too, 
The build job relies on `semantic-release-action`, to get the image tag, and for whatever reason the CI build has been flakey.

Unfortunately, subsequent reruns of the build stage (intended to address the flakiness)  fail, because `semantic-release-action` no-ops on the re-run of the job, as there's no new commits, and as a result, the requisite output isn't available.

Ideally, this ci job should be idempotent, as it's usually the basis or condition for subsequent CI jobs
