### ISSUE TITLE
BreakingChange: not working

### ISSUE THREAD

**Issue by naveenkumarvr** [codfish/semantic-release-action#180]
Helo Team, 

Thanks for the useful action.

I'm trying to release major of my app. when I add "Breaking Change:" in my commit the major version is not getting updated. I tried all the below things.
 
  BREAKING CHANGE:
  BREAKING CHANES:
  ! BREAKING CHANGE:
  Also tried adding commit analyzer plugin and rules

Nothing works. Please guide me on how to bump up major version using the codefish action

**Comment by franky47** [comment]
Is your `BREAKING CHANGE: description` block at the footer of the commit message?
https://semantic-release.gitbook.io/semantic-release/#commit-message-format

Unfortunately, this makes it not play well with auto-close messages, like `Fixes #123` and the like.
