### ISSUE TITLE
Lifecycle scripts are not running

### ISSUE THREAD

**Issue by franky47** [codfish/semantic-release-action#181]
I'm trying to run a script in the NPM `prepack` lifecycle hook script, as recommended by the [semantic release docs](https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-use-a-npm-build-script-that-requires-the-package.jsons-version), to sign the artifacts right before they are packed for publishing.

It executes fine when running semantic-release locally, but not when running in this action. Here's an example of the error message being returned:
https://github.com/47ng/sceau/actions/runs/3685799334/jobs/6237204982#step:8:66

```
npm WARN lifecycle sceau@1.0.0-beta.7~prepack: cannot run in wd sceau@1.0.0-beta.7 node ./dist/cli.js sign (wd=/github/workspace)
```

A possible lead could be user permissions when running in a Docker context:
https://stackoverflow.com/questions/57008653/why-does-npm-not-run-prepublishonly-in-docker

**Comment by codfish** [comment]
@franky47 sorry I'm so late to see this, I had to fine tune my github notifications so these new issues come through moving forward. Your action run logs have expired, are you still using the action and if so do you have a newer run to send over so I could take a look?

**Comment by franky47** [comment]
I'm no longer using this action, as I had to fine-tune my semantic-release config and so I needed to run it locally. So now GHA only invokes the local version via `npx semantic-release`.
