### ISSUE TITLE
Feature Request: Change Working Directory

### ISSUE THREAD

**Issue by jessebye** [codfish/semantic-release-action#209]
As mentioned in #174 , it is possible to specify the `pkgRoot` to change the working directory for the `npm` publishing step specifically. However, we have found this doesn't address all project scenarios. We'd prefer that this action have an input for `working-directory` (similar to a run step's [working-directory](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory) input) that would change the working directory for all steps of the semantic-release action.

**Comment by codfish** [comment]
hey @jessebye, apologies for the delayed response—would you be able to take a shot at this? I'm not going to be able to get to this promptly at the moment unfortunately

**Comment by jessebye** [comment]
@codfish no worries! please check out #210
